snippet skel
FROM ${1:base}

ARG BUILD_DATE
ARG VCS_REF

LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/${2:repo}.git" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.schema-version="1.0.0-rc1"

WORKDIR ${3:/documents}

${0}

ENTRYPOINT ["${4:/bin/sh}"]
endsnippet
